name:Ema_chatbot
on:  [push]
jobs:
  build:
    runs-on:ubuntu-latest
    steps:
        -  name: Checkout Repo
           uses: actions/checkout@v3
        -  name: setup Repo
           uses: acions/setup-python@v4
           with: python-version: '3.10'
        -  name: Install Dependency
           run:  |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
        -  name: run app
           run: |
           streamlit run app.py
           
    
